# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybugreport', '0003_project_is_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_del',
            field=models.BooleanField(default=0),
        ),
    ]
